name: Deploy to EC2

on:
  push:
    branches:
        - main
  # or specify other triggers, e.g. pull_request or specific branches.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: 34.207.122.207
            username: ec2-user
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                cd ~/HereNow-2
                git pull origin main
                npm install
                pm2 restart "herenow"
